util.AddNetworkString( "disableAbilites" )
util.AddNetworkString( "RangedActivated" )
util.AddNetworkString( "UltActivated" )
util.AddNetworkString( "AOEActivated" )
util.AddNetworkString( "MeleeActivated" )